application: subtome-static
version: 3
runtime: python27
api_version: 1
threadsafe: yes

handlers:

- url: /
  static_files: index.html
  upload: index.html

- url: /index.html
  static_files: index.html
  upload: index.html

- url: /developers.html
  static_files: developers.html
  upload: developers.html

- url: /done.html
  static_files: done.html
  upload: done.html

- url: /publishers.html
  static_files: publishers.html
  upload: publishers.html

- url: /register.html
  static_files: register.html
  upload: register.html

- url: /register-no-ui.html
  static_files: register-no-ui.html
  upload: register-no-ui.html

- url: /settings.html
  static_files: settings.html
  upload: settings.html

- url: /subscribe.html
  static_files: subscribe.html
  upload: subscribe.html

- url: /store.html
  static_files: store.html
  upload: store.html

- url: /load.js
  static_files: load.js
  upload: load.js

- url: /src
  static_dir: src

- url: /img
  static_dir: img

- url: /build
  static_dir: build
